
services:
  jenkins:
    image: maikol555/jenkinsultimate:1.0
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - /home/devops/projects/curso-maikol/demojenkins/jenkins/jenkins_home:/var/jenkins_home

